name: Hygiene

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  quality-control:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Audit
        run: npm run audit

      - name: Build
        run: export NODE_OPTIONS="--max_old_space_size=4096" && npm run build
