name: Release

on:
  push:
    branches:
      - main

jobs:
  check:
    uses: ./.github/workflows/check.yml
    if: github.event.head_commit.message != 'version packages'
    secrets: inherit

  version:
    needs: check
    uses: ./.github/workflows/version.yml
    secrets: inherit

  deploy:
    needs: check
    uses: ./.github/workflows/deploy.yml
    secrets: inherit

  publish:
    uses: ./.github/workflows/publish.yml
    if: github.event.head_commit.message == 'version packages'
    secrets: inherit
