name: Release

on:
  workflow_call:

jobs:
  version:
    name: Version Packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npm ci

      - name: Version Packages
        uses: changesets/action@v1
        with:
          commit: version packages
          publish: echo "This step is not configured for publishing."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
